version: '3'

#
# docker-compose.yaml
#   Override compose file for running with an externally provided cluster
#

services:
  # Disable running DSE in this Docker compose
  dse:
    entrypoint: ["echo", "Service DSE disabled from running in Docker - external cluster in use"]


  # Passing cluster contact points into each of the following images
  dse-config:
    environment:
      KILLRVIDEO_DSE_CONTACT_POINTS: $KILLRVIDEO_DSE_CONTACT_POINTS

  backend:
    environment:
      KILLRVIDEO_DSE_CONTACTPOINTS: $KILLRVIDEO_DSE_CONTACT_POINTS

  generator:
    environment:
      KILLRVIDEO_DSE_CONTACT_POINTS: $KILLRVIDEO_DSE_CONTACT_POINTS

  web:
    environment:
      KILLRVIDEO_DSE_CONTACT_POINTS: $KILLRVIDEO_DSE_CONTACT_POINTS
