version: '3'

#
# docker-compose-ops-center.yaml
#   Override compose file to add DataStax OpsCenter to the standard KillrVideo infrastructure configuration
#

services:

  # Override DSE configuration to allow reporting to opscenter
  dse:
    links:
    - opscenter

  # OpsCenter
  opscenter:
    image: datastax/dse-opscenter
    ports:
    - "8888:8888"
    environment:
      SERVICE_8888_NAME: opscenter
      DS_LICENSE: accept
