version: '3'
services:

  dse:
    ports:
      - "9103:9103" # Exposes metrics port
    volumes:
      # push promethus config to node for insights support
      - "./dse/prometheus.conf:/opt/dse/resources/dse/collectd/etc/collectd/prometheus.conf"

  prometheus:
    image: "prom/prometheus:v2.4.3"
    ports:
      - "9090:9090"
    volumes:
      - "${PROMETHEUS_DATA_DIR:-prometheus}:/prometheus"
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "./prometheus/tg_dse.json:/etc/prometheus/tg_dse.json"

  grafana:
    image: "grafana/grafana:5.3.2"
    ports:
      - "3100:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_AUTH_ANONYMOUS_ENABLED: "true"
    volumes:
      - "${GRAFANA_DATA_DIR:-grafana}:/var/lib/grafana"
      - "./grafana/prometheus-datasource.yaml:/etc/grafana/provisioning/datasources/prometheus-datasource.yaml"
      - "./grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml"
      - "./grafana/dashboards:/var/lib/grafana/dashboards:ro"

volumes:
  dse:
  grafana:
  prometheus:
